---
steps:
- name: golang:1.19
  entrypoint: /bin/bash
  args: 
      - -c
      - |
        make
artifacts:
  objects:
    location: gs://puerco-chainguard-public/test-build/${SHORT_SHA}/
    paths:
      - hello
      - README.md

