---
steps:
- name: golang:1.19
  entrypoint: /bin/bash
  args: 
      - -c
      - |
        make
- name: 'gcr.io/cloud-builders/gcloud-slim'
  args:
    - 'pubsub'
    - 'topics'
    - 'publish'
    - 'projects/puerco-chainguard/topics/slsa'
    - '--message'
    - "{\"project\": \"${PROJECT_ID}\", \"build\":\"${BUILD_ID}\"}"

artifacts:
  objects:
    location: gs://puerco-chainguard-public/test-build/${SHORT_SHA}/
    paths:
      - hello
      - README.md

