name: Build SLSA Attestation
on:
  workflow_run:
    types: [completed]
    workflows: [Build]

jobs:
  attest:
    name: Attest Workflow Run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
    - uses: actions/checkout@v3
      with:
        repository: puerco/tejolote
        path: .ci/src/tejolote
    
    - name: Install Go    
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        cache: true
        cache-dependency-path: .ci/src/tejolote/go.sum
    - name: Build Tejolote Attester
      run: |
        pwd
        (cd .ci/src/tejolote; go build -o ../../tejolote cmd/tejolote/main.go)
        rm -rfv .ci/src/tejolote
    - name: Attest Run
      env:
        COSIGN_EXPERIMENTAL: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pwd
        ./.ci/tejolote attest --sign github://puerco/tejolote-test/${{ github.event.workflow_run.id }} 
