# Sample Project builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Test Project
    runs-on: ubuntu-latest
    steps:
    - name: Install Go    
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: puerco/tejolote
        path: .ci/src/tejolote
    - run: |
        pwd
        (cd .ci/src/tejolote; go build -o ../../tejolote cmd/tejolote/main.go)
        rm -rfv .ci/src/tejolote
    
    - run: |
        pwd
        ./tejolote
