# Sample Project builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Test Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: puerco/tejolote
        path: tejolote
    - name: Install Go    
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: |
        cd tejolote
        go build -o tejolote cmd/tejolote/main.go
        ./tejolote
